---
title: "Leaves_high_abun_manyGLMs"
format: html
editor: visual
---

```{r}
#load libraries
library(dplyr)
library(tidyr)
library(ggplot2)
library(car)
library(DHARMa)
library(vegan)
library(magrittr)
library(mvabund)
library(performance)
library(emmeans)
library(utils)
```

#Import data
```{r}
Leaves <- read.csv("ASV_deseq2_leaves_highabun.csv")
Leaves.matrix <- Leaves[3:107  ] # just the community data
Leaves.factors <- Leaves[1:2] # just the factors
Leaves.factors$Leaf_Status <- as.factor(Leaves.factors$Leaf_Status)

Leaves.mva=mvabund(Leaves.matrix) # makes an mvabund object with the bacterial data (the transposed matrix of RAW COUNTS)

```

# Initial model fitting
```{r}
# Plot the data - look at the differences between ASVs between samples 
plot(Leaves.mva ~ Leaves.factors$Leaf_Status, type="bx", cex.axis=0.55, legend=F) # Box plot 
#looks like the most abundant ASVS do have differences 

# Lets fit the model
nb.1 = manyglm(Leaves.mva ~ Leaf_Status, data=Leaves.factors)
#this uses the default'negative biom' model

# Check the model fitting plotting the residuals
plot(nb.1, n.vars=15) 
```

# PERMANOVA
```{r}
# Run the statistical test
dat.aov = anova(nb.1, nBoot=1000, p.uni="adjusted") 
saveRDS(dat.aov, file= "leaves.dat.aov.high.rds")

dat.aov <- readRDS("leaves.dat.aov.high.rds")

# Get the output of the test
dat.aov$table # multivariate table
#there is a marginal signif difference - we knew this from our PERMANOVA in primer 

dat.aov$uni.test # univariate test statistics
# Note that the output is quite horrible here 

dat.aov$uni.p # univariate adjusted p values- note that the output is quite horrible here
```

#Processing PERMANOVA results
```{r}
# Is any of these significantly different? (i.e. p<0.05, p<0.1)
any(dat.aov$uni.p[2,]<0.05) 
# Yes, some bacterial classes differed between species

# We can visualise this by plotting those p-values from smaller to larger
plot(sort(dat.aov$uni.p[2,]), main="Sorted univariate P values")
abline(h=0.1, lty=2, col="red") # line at the 0.1 cut-off

# Around 5-6 classes around p = 0.05. Who are these?
diffs=which(dat.aov$uni.p[2,]<0.05)
diffs
```

#Extract p values
```{r}
#Extract the test statistic and p values for each of these ASVs
stat_dat_aov.a <- t(dat.aov$uni.test) # univariate test statistics
p_dat_aov.a <- t(dat.aov$uni.p) # univariate test statistics; p-values

# Convert the matrix to a dataframe
stat_dat_aov_df.a <- as.data.frame(stat_dat_aov.a)
p_dat_aov_df.a <- as.data.frame(p_dat_aov.a)
```

#Save data
```{r}
# Save the dataframe as a CSV file
write.csv(p_dat_aov_df.a, "C:/Users/z3532738/OneDrive - UNSW/UNSW ra/Student Data/Lizzy/Bioinformatics/Post_processing_outputs/R graphs/p_leaves.a.csv")
write.csv(stat_dat_aov_df.a, "C:/Users/z3532738/OneDrive - UNSW/UNSW ra/Student Data/Lizzy/Bioinformatics/Post_processing_outputs/R graphs/stat_leaves.a.csv")
#combine these two excel files into one, and then sort by "p value". 
#copy paste the ASVs for significant values (p<0.01) into a table and put that table in your thesis 
#this final file is called pvalues_leaves_highabundance
#to make a nice ggplot2 one, we need to fix the dataset first. if you did this for all.abundance you dont need to repeat this step
```

# Start to build plot
```{r}
#import data with ASVS as rows 
leaves_manyglm <- read.csv("leaves.manyglm.csv", header = TRUE, stringsAsFactors = FALSE)

#Change asv table from wide to long format with column names Sequence, ASV, SampleID and Abundance (in that order)
asv_table_ra_long <- leaves_manyglm %>% 
  pivot_longer(cols = -1, # Pivot all columns except the first one (ID column = ASV)
               names_to = "Sample", # New column for the names of the original columns
               values_to = "Relabun")
```

# Make many GLMs
```{r}
leaves_manyglm <- read.csv("leaves_long_edited.csv")
mean_relabun <- leaves_manyglm %>%
  group_by(SampleID, Leaf_status) %>%
  summarise(Mean_Relabun = mean(Relabun, na.rm = TRUE),SEM = sd(Relabun, na.rm = TRUE) / sqrt(n()))

high.abun.plot <- read.csv("high.abundance.plot.csv")
high.abun.plot$Leaf_Status <- factor(high.abun.plot$Leaf_Status, levels = c("Healthy", "Unhealthy"), labels = c("Healthy", "Unhealthy")) 
```

# Plot high abundance ASVs

```{r}
# Setting colors
mycols2 <- c("Healthy" = "#65B540", "Unhealthy" = "#654321")

## Plot
leaf2 <- ggplot(high.abun.plot, aes(x = SampleID, y = Relabun, fill = Leaf_Status)) +
  geom_bar(stat = "identity", width = 0.9, position = position_dodge(width = -0.8), alpha = 0.8) +
  xlab("") + ylab("\nRelative abundance (%)") +
   scale_fill_manual(values = mycols2) +
  geom_errorbar(aes(ymin = Relabun - SE, ymax = Relabun + SE), width = 0.4,
                position = position_dodge(width = -0.8)) +
  labs(title = "B)",fill = "Leaf Status") +  # Change legend title here
  theme(axis.text.y = element_text(size = 12), 
        axis.title.y = element_text(size = 12, face = 'bold'),
        axis.text.x = element_text(size = 14), 
        axis.title.x = element_text(size = 12, face = 'bold'),
        legend.position = "bottom", 
        legend.direction = "horizontal",
        legend.title =  element_text(size = 12),  # Style the legend title, 
        legend.text = element_text(size = 11),
        panel.background = element_rect(fill = "white", colour = "black"),
        strip.text = element_text(size = 15, face = "bold")) +
  coord_flip()  # Flip coordinates for horizontal bars

leaf2
```
